In [1]:
import pandas as pd
import pymongo
from bson.json_util import dumps
import json
from config import user, password
import random

from bs4 import BeautifulSoup

In [2]:
# Use a random punk_id as dummy imput for id_selection
id_selection = str(random.randrange(0,10000,1))
id_selection

'8889'

In [3]:
# construct the connection string for Atlas
CONNECTION_STRING = "mongodb+srv://"+ user + ":" + password +"@cluster0.wddnt.mongodb.net/crypto_punks_mdb?retryWrites=true&w=majority"

# Create the connection client to Atlas
client = pymongo.MongoClient(CONNECTION_STRING) 

# indicate the database to access in Atlas
db = pymongo.database.Database(client,'crypto_punks_mdb')
  
# assign the connection to the database and collection to a variable (i.e. this still is not 'reading' 
# the data from the database)
crypto_punks = pymongo.collection.Collection(db, 'crypto_punks_col')
attributes = pymongo.collection.Collection(db, 'attributes_col')
      
# search the database for the unique punk_id value provided as input to 
# the function and assign the output to a variable. The output will be an object.
crypto_punks_data = json.loads(dumps(crypto_punks.find({"punk_id":id_selection})))
attributes_data = json.loads(dumps(attributes.find()))

In [4]:
# Inspect the attributes_data
attributes_data

[{'_id': {'$oid': '61eb61559671d68c66ea53fb'},
  'Attribute': 'Alien',
  'counts': '9'},
 {'_id': {'$oid': '61eb61559671d68c66ea53fc'},
  'Attribute': 'Ape',
  'counts': '24'},
 {'_id': {'$oid': '61eb61559671d68c66ea53fd'},
  'Attribute': 'Female',
  'counts': '3840'},
 {'_id': {'$oid': '61eb61559671d68c66ea53fe'},
  'Attribute': 'Male',
  'counts': '6039'},
 {'_id': {'$oid': '61eb61559671d68c66ea53ff'},
  'Attribute': 'Zombie',
  'counts': '88'},
 {'_id': {'$oid': '61eb61559671d68c66ea5400'},
  'Attribute': '0 accessories',
  'counts': '8'},
 {'_id': {'$oid': '61eb61559671d68c66ea5401'},
  'Attribute': '1 accessories',
  'counts': '333'},
 {'_id': {'$oid': '61eb61559671d68c66ea5402'},
  'Attribute': '2 accessories',
  'counts': '3560'},
 {'_id': {'$oid': '61eb61559671d68c66ea5403'},
  'Attribute': '3 accessories',
  'counts': '4501'},
 {'_id': {'$oid': '61eb61559671d68c66ea5404'},
  'Attribute': '4 accessories',
  'counts': '1420'},
 {'_id': {'$oid': '61eb61559671d68c66ea5405'},
  'Attribute': '5 accessories',
  'counts': '166'},
 {'_id': {'$oid': '61eb61559671d68c66ea5406'},
  'Attribute': '6 accessories',
  'counts': '11'},
 {'_id': {'$oid': '61eb61559671d68c66ea5407'},
  'Attribute': '7 accessories',
  'counts': '1'},
 {'_id': {'$oid': '61eb61559671d68c66ea5408'},
  'Attribute': 'Green Eye Shadow',
  'counts': '271'},
 {'_id': {'$oid': '61eb61559671d68c66ea5409'},
  'Attribute': 'Earring',
  'counts': '2459'},
 {'_id': {'$oid': '61eb61559671d68c66ea540a'},
  'Attribute': 'Blonde Bob',
  'counts': '147'},
 {'_id': {'$oid': '61eb61559671d68c66ea540b'},
  'Attribute': 'Smile',
  'counts': '238'},
 {'_id': {'$oid': '61eb61559671d68c66ea540c'},
  'Attribute': 'Mohawk',
  'counts': '441'},
 {'_id': {'$oid': '61eb61559671d68c66ea540d'},
  'Attribute': 'Wild Hair',
  'counts': '447'},
 {'_id': {'$oid': '61eb61559671d68c66ea540e'},
  'Attribute': 'Nerd Glasses',
  'counts': '572'},
 {'_id': {'$oid': '61eb61559671d68c66ea540f'},
  'Attribute': 'Pipe',
  'counts': '317'},
 {'_id': {'$oid': '61eb61559671d68c66ea5410'},
  'Attribute': 'Big Shades',
  'counts': '535'},
 {'_id': {'$oid': '61eb61559671d68c66ea5411'},
  'Attribute': 'Goat',
  'counts': '295'},
 {'_id': {'$oid': '61eb61559671d68c66ea5412'},
  'Attribute': 'Purple Eye Shadow',
  'counts': '262'},
 {'_id': {'$oid': '61eb61559671d68c66ea5413'},
  'Attribute': 'Half Shaved',
  'counts': '147'},
 {'_id': {'$oid': '61eb61559671d68c66ea5414'},
  'Attribute': 'Do-rag',
  'counts': '300'},
 {'_id': {'$oid': '61eb61559671d68c66ea5415'},
  'Attribute': 'Wild White Hair',
  'counts': '136'},
 {'_id': {'$oid': '61eb61559671d68c66ea5416'},
  'Attribute': 'Spots',
  'counts': '124'},
 {'_id': {'$oid': '61eb61559671d68c66ea5417'},
  'Attribute': 'Clown Eyes Blue',
  'counts': '384'},
 {'_id': {'$oid': '61eb61559671d68c66ea5418'},
  'Attribute': 'Messy Hair',
  'counts': '460'},
 {'_id': {'$oid': '61eb61559671d68c66ea5419'},
  'Attribute': 'Luxurious Beard',
  'counts': '286'},
 {'_id': {'$oid': '61eb61559671d68c66ea541a'},
  'Attribute': 'Clown Nose',
  'counts': '212'},
 {'_id': {'$oid': '61eb61559671d68c66ea541b'},
  'Attribute': 'Police Cap',
  'counts': '203'},
 {'_id': {'$oid': '61eb61559671d68c66ea541c'},
  'Attribute': 'Big Beard',
  'counts': '146'},
 {'_id': {'$oid': '61eb61559671d68c66ea541d'},
  'Attribute': 'Blue Eye Shadow',
  'counts': '266'},
 {'_id': {'$oid': '61eb61559671d68c66ea541e'},
  'Attribute': 'Black Lipstick',
  'counts': '617'},
 {'_id': {'$oid': '61eb61559671d68c66ea541f'},
  'Attribute': 'Clown Eyes Green',
  'counts': '382'},
 {'_id': {'$oid': '61eb61559671d68c66ea5420'},
  'Attribute': 'Straight Hair Dark',
  'counts': '148'},
 {'_id': {'$oid': '61eb61559671d68c66ea5421'},
  'Attribute': 'Blonde Short',
  'counts': '129'},
 {'_id': {'$oid': '61eb61559671d68c66ea5422'},
  'Attribute': 'Purple Lipstick',
  'counts': '655'},
 {'_id': {'$oid': '61eb61559671d68c66ea5423'},
  'Attribute': 'Straight Hair Blonde',
  'counts': '144'},
 {'_id': {'$oid': '61eb61559671d68c66ea5424'},
  'Attribute': 'Pilot Helmet',
  'counts': '54'},
 {'_id': {'$oid': '61eb61559671d68c66ea5425'},
  'Attribute': 'Hot Lipstick',
  'counts': '696'},
 {'_id': {'$oid': '61eb61559671d68c66ea5426'},
  'Attribute': 'Regular Shades',
  'counts': '527'},
 {'_id': {'$oid': '61eb61559671d68c66ea5427'},
  'Attribute': 'Stringy Hair',
  'counts': '463'},
 {'_id': {'$oid': '61eb61559671d68c66ea5428'},
  'Attribute': 'Small Shades',
  'counts': '378'},
 {'_id': {'$oid': '61eb61559671d68c66ea5429'},
  'Attribute': 'Frown',
  'counts': '261'},
 {'_id': {'$oid': '61eb61559671d68c66ea542a'},
  'Attribute': 'Eye Mask',
  'counts': '293'},
 {'_id': {'$oid': '61eb61559671d68c66ea542b'},
  'Attribute': 'Muttonchops',
  'counts': '303'},
 {'_id': {'$oid': '61eb61559671d68c66ea542c'},
  'Attribute': 'Bandana',
  'counts': '481'},
 {'_id': {'$oid': '61eb61559671d68c66ea542d'},
  'Attribute': 'Horned Rim Glasses',
  'counts': '535'},
 {'_id': {'$oid': '61eb61559671d68c66ea542e'},
  'Attribute': 'Crazy Hair',
  'counts': '414'},
 {'_id': {'$oid': '61eb61559671d68c66ea542f'},
  'Attribute': 'Classic Shades',
  'counts': '502'},
 {'_id': {'$oid': '61eb61559671d68c66ea5430'},
  'Attribute': 'Handlebars',
  'counts': '263'},
 {'_id': {'$oid': '61eb61559671d68c66ea5431'},
  'Attribute': 'Mohawk Dark',
  'counts': '429'},
 {'_id': {'$oid': '61eb61559671d68c66ea5432'},
  'Attribute': 'Dark Hair',
  'counts': '157'},
 {'_id': {'$oid': '61eb61559671d68c66ea5433'},
  'Attribute': 'Peak Spike',
  'counts': '303'},
 {'_id': {'$oid': '61eb61559671d68c66ea5434'},
  'Attribute': 'Normal Beard Black',
  'counts': '289'},
 {'_id': {'$oid': '61eb61559671d68c66ea5435'},
  'Attribute': 'Cap',
  'counts': '351'},
 {'_id': {'$oid': '61eb61559671d68c66ea5436'},
  'Attribute': 'VR',
  'counts': '332'},
 {'_id': {'$oid': '61eb61559671d68c66ea5437'},
  'Attribute': 'Frumpy Hair',
  'counts': '442'},
 {'_id': {'$oid': '61eb61559671d68c66ea5438'},
  'Attribute': 'Cigarette',
  'counts': '961'},
 {'_id': {'$oid': '61eb61559671d68c66ea5439'},
  'Attribute': 'Normal Beard',
  'counts': '292'},
 {'_id': {'$oid': '61eb61559671d68c66ea543a'},
  'Attribute': 'Red Mohawk',
  'counts': '147'},
 {'_id': {'$oid': '61eb61559671d68c66ea543b'},
  'Attribute': 'Shaved Head',
  'counts': '300'},
 {'_id': {'$oid': '61eb61559671d68c66ea543c'},
  'Attribute': 'Chinstrap',
  'counts': '282'},
 {'_id': {'$oid': '61eb61559671d68c66ea543d'},
  'Attribute': 'Mole',
  'counts': '644'},
 {'_id': {'$oid': '61eb61559671d68c66ea543e'},
  'Attribute': 'Knitted Cap',
  'counts': '419'},
 {'_id': {'$oid': '61eb61559671d68c66ea543f'},
  'Attribute': 'Fedora',
  'counts': '186'},
 {'_id': {'$oid': '61eb61559671d68c66ea5440'},
  'Attribute': 'Shadow Beard',
  'counts': '526'},
 {'_id': {'$oid': '61eb61559671d68c66ea5441'},
  'Attribute': 'Straight Hair',
  'counts': '151'},
 {'_id': {'$oid': '61eb61559671d68c66ea5442'},
  'Attribute': 'Hoodie',
  'counts': '259'},
 {'_id': {'$oid': '61eb61559671d68c66ea5443'},
  'Attribute': 'Eye Patch',
  'counts': '461'},
 {'_id': {'$oid': '61eb61559671d68c66ea5444'},
  'Attribute': 'Headband',
  'counts': '406'},
 {'_id': {'$oid': '61eb61559671d68c66ea5445'},
  'Attribute': 'Cowboy Hat',
  'counts': '142'},
 {'_id': {'$oid': '61eb61559671d68c66ea5446'},
  'Attribute': 'Tassle Hat',
  'counts': '178'},
 {'_id': {'$oid': '61eb61559671d68c66ea5447'},
  'Attribute': '3D Glasses',
  'counts': '286'},
 {'_id': {'$oid': '61eb61559671d68c66ea5448'},
  'Attribute': 'Mustache',
  'counts': '288'},
 {'_id': {'$oid': '61eb61559671d68c66ea5449'},
  'Attribute': 'Vape',
  'counts': '272'},
 {'_id': {'$oid': '61eb61559671d68c66ea544a'},
  'Attribute': 'Choker',
  'counts': '48'},
 {'_id': {'$oid': '61eb61559671d68c66ea544b'},
  'Attribute': 'Pink With Hat',
  'counts': '95'},
 {'_id': {'$oid': '61eb61559671d68c66ea544c'},
  'Attribute': 'Welding Goggles',
  'counts': '86'},
 {'_id': {'$oid': '61eb61559671d68c66ea544d'},
  'Attribute': 'Vampire Hair',
  'counts': '147'},
 {'_id': {'$oid': '61eb61559671d68c66ea544e'},
  'Attribute': 'Mohawk Thin',
  'counts': '441'},
 {'_id': {'$oid': '61eb61559671d68c66ea544f'},
  'Attribute': 'Tiara',
  'counts': '55'},
 {'_id': {'$oid': '61eb61559671d68c66ea5450'},
  'Attribute': 'Front Beard Dark',
  'counts': '260'},
 {'_id': {'$oid': '61eb61559671d68c66ea5451'},
  'Attribute': 'Cap Forward',
  'counts': '254'},
 {'_id': {'$oid': '61eb61559671d68c66ea5452'},
  'Attribute': 'Gold Chain',
  'counts': '169'},
 {'_id': {'$oid': '61eb61559671d68c66ea5453'},
  'Attribute': 'Purple Hair',
  'counts': '165'},
 {'_id': {'$oid': '61eb61559671d68c66ea5454'},
  'Attribute': 'Beanie',
  'counts': '44'},
 {'_id': {'$oid': '61eb61559671d68c66ea5455'},
  'Attribute': 'Clown Hair Green',
  'counts': '148'},
 {'_id': {'$oid': '61eb61559671d68c66ea5456'},
  'Attribute': 'Pigtails',
  'counts': '94'},
 {'_id': {'$oid': '61eb61559671d68c66ea5457'},
  'Attribute': 'Silver Chain',
  'counts': '156'},
 {'_id': {'$oid': '61eb61559671d68c66ea5458'},
  'Attribute': 'Front Beard',
  'counts': '273'},
 {'_id': {'$oid': '61eb61559671d68c66ea5459'},
  'Attribute': 'Rosy Cheeks',
  'counts': '128'},
 {'_id': {'$oid': '61eb61559671d68c66ea545a'},
  'Attribute': 'Orange Side',
  'counts': '68'},
 {'_id': {'$oid': '61eb61559671d68c66ea545b'},
  'Attribute': 'Wild Blonde',
  'counts': '144'},
 {'_id': {'$oid': '61eb61559671d68c66ea545c'},
  'Attribute': 'Buck Teeth',
  'counts': '78'},
 {'_id': {'$oid': '61eb61559671d68c66ea545d'},
  'Attribute': 'Top Hat',
  'counts': '115'},
 {'_id': {'$oid': '61eb61559671d68c66ea545e'},
  'Attribute': 'Medical Mask',
  'counts': '175'}]

In [5]:
# Inspect the crypto_punks_data
crypto_punks_data

[{'_id': {'$oid': '61e486b7c34e5e3a5c6afa67'},
  'punk_id': '8889',
  'type': 'Male',
  'accessories': ['Luxurious Beard',
   'Peak Spike',
   'Vape',
   'Classic Shades',
   'Smile'],
  'type_ML': '0',
  'type_PRED': '0',
  'glasses_ML': '1',
  'glasses_PRED': '1',
  'info_URL': 'https://www.larvalabs.com/cryptopunks/details/8889',
  'image_bitmap': [[[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [139, 83, 44, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [139, 83, 44, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [92, 57, 15, 255],
    [92, 57, 15, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [92, 57, 15, 255],
    [92, 57, 15, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [199, 117, 20, 255],
    [199, 117, 20, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [199, 117, 20, 255],
    [199, 117, 20, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [105, 47, 8, 255],
    [105, 47, 8, 255],
    [0, 0, 0, 255],
    [89, 89, 89, 255],
    [89, 89, 89, 255],
    [89, 89, 89, 255],
    [89, 89, 89, 255],
    [89, 89, 89, 255],
    [0, 64, 255, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]],
   [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [113, 63, 29, 255],
    [0, 0, 0, 255],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]]]}]

In [6]:
# Convert the json strings to dataframes
punks_df = pd.DataFrame(crypto_punks_data)
punks_df = punks_df.drop(columns=["_id"])
punks_df

,punk_id,type,accessories,type_ML,type_PRED,glasses_ML,glasses_PRED,info_URL,image_bitmap
0,8889,Male,"[Luxurious Beard, Peak Spike, Vape, Classic Sh...",0,0,1,1,https://www.larvalabs.com/cryptopunks/details/...,"[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0..."

In [7]:
# Convert the json strings to dataframes
attributes_df = pd.DataFrame(attributes_data)
attributes_df = attributes_df.drop(columns=["_id"])
attributes_df.head(30)

            Attribute counts
0               Alien      9
1                 Ape     24
2              Female   3840
3                Male   6039
4              Zombie     88
5       0 accessories      8
6       1 accessories    333
7       2 accessories   3560
8       3 accessories   4501
9       4 accessories   1420
10      5 accessories    166
11      6 accessories     11
12      7 accessories      1
13   Green Eye Shadow    271
14            Earring   2459
15         Blonde Bob    147
16              Smile    238
17             Mohawk    441
18          Wild Hair    447
19       Nerd Glasses    572
20               Pipe    317
21         Big Shades    535
22               Goat    295
23  Purple Eye Shadow    262
24        Half Shaved    147
25             Do-rag    300
26    Wild White Hair    136
27              Spots    124
28    Clown Eyes Blue    384
29         Messy Hair    460

In [8]:
# Create the summary punk_facts dataframe
# 1. Create an empty list for all the attributes in the punk_id
punk_attribute_list = []

# 2. Populate the list
punk_attribute_list.append(punks_df.at[0,"type"])
punk_accessories = punks_df.at[0,"accessories"]
for accessory in punk_accessories:
    punk_attribute_list.append(accessory)
punk_attribute_list.append(str(len(punk_accessories))+" accessories")
# 3. Inspect the list
punk_attribute_list

['Male',
 'Luxurious Beard',
 'Peak Spike',
 'Vape',
 'Classic Shades',
 'Smile',
 '5 accessories']

In [9]:
punk_facts_df = attributes_df[attributes_df['Attribute'].isin(punk_attribute_list)]
punk_facts_df

          Attribute counts
3              Male   6039
10    5 accessories    166
16            Smile    238
30  Luxurious Beard    286
52   Classic Shades    502
56       Peak Spike    303
78             Vape    272

In [10]:
# reset index
punk_facts_df.reset_index(drop=True, inplace=True)
punk_facts_df

         Attribute counts
0             Male   6039
1    5 accessories    166
2            Smile    238
3  Luxurious Beard    286
4   Classic Shades    502
5       Peak Spike    303
6             Vape    272

In [11]:
# Inspect data types
punk_facts_df.dtypes

Attribute    object
counts       object
dtype: object

In [12]:
punk_facts_df["counts"] = pd.to_numeric(punk_facts_df["counts"])

/var/folders/lc/bd2hdpn53fnd_gtfy8gt049h0000gn/T/ipykernel_45117/3626927956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  punk_facts_df["counts"] = pd.to_numeric(punk_facts_df["counts"])

In [13]:
# Inspect data types
punk_facts_df.dtypes

Attribute    object
counts        int64
dtype: object

In [14]:
# Add rarity scores
for row in range(len(punk_facts_df)):
    punk_facts_df.at[row,"Rarity %"] = punk_facts_df.at[row,"counts"]/10000 * 100
    punk_facts_df.at[row,"Rarity Score"] = 10000 / punk_facts_df.at[row,"counts"]
    
punk_facts_df

/Users/ignacioguerra/miniforge3/lib/python3.9/site-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/Users/ignacioguerra/miniforge3/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

         Attribute  counts  Rarity %  Rarity Score
0             Male    6039     60.39      1.655903
1    5 accessories     166      1.66     60.240964
2            Smile     238      2.38     42.016807
3  Luxurious Beard     286      2.86     34.965035
4   Classic Shades     502      5.02     19.920319
5       Peak Spike     303      3.03     33.003300
6             Vape     272      2.72     36.764706

In [15]:
# rename column
punk_facts_df.rename(columns = {"counts":"Punks that Share this Attribute"}, inplace = True)
punk_facts_df

/Users/ignacioguerra/miniforge3/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

         Attribute  Punks that Share this Attribute  Rarity %  Rarity Score
0             Male                             6039     60.39      1.655903
1    5 accessories                              166      1.66     60.240964
2            Smile                              238      2.38     42.016807
3  Luxurious Beard                              286      2.86     34.965035
4   Classic Shades                              502      5.02     19.920319
5       Peak Spike                              303      3.03     33.003300
6             Vape                              272      2.72     36.764706

In [16]:
punk_facts_df = punk_facts_df.set_index("Attribute")
punk_facts_df

                 Punks that Share this Attribute  Rarity %  Rarity Score
Attribute
Male                                        6039     60.39      1.655903
5 accessories                                166      1.66     60.240964
Smile                                        238      2.38     42.016807
Luxurious Beard                              286      2.86     34.965035
Classic Shades                               502      5.02     19.920319
Peak Spike                                   303      3.03     33.003300
Vape                                         272      2.72     36.764706

In [17]:
# Convert the dataframe to html and assign it to a variable
#punk_facts = punk_facts_df.to_html()


#1. create bs object
punk_facts = BeautifulSoup(punk_facts_df.to_html())
punk_facts

<html><body><table border="1" class="dataframe">
<thead>
<tr style="text-align: right;">
<th></th>
<th>Punks that Share this Attribute</th>
<th>Rarity %</th>
<th>Rarity Score</th>
</tr>
<tr>
<th>Attribute</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<th>Male</th>
<td>6039</td>
<td>60.39</td>
<td>1.655903</td>
</tr>
<tr>
<th>5 accessories</th>
<td>166</td>
<td>1.66</td>
<td>60.240964</td>
</tr>
<tr>
<th>Smile</th>
<td>238</td>
<td>2.38</td>
<td>42.016807</td>
</tr>
<tr>
<th>Luxurious Beard</th>
<td>286</td>
<td>2.86</td>
<td>34.965035</td>
</tr>
<tr>
<th>Classic Shades</th>
<td>502</td>
<td>5.02</td>
<td>19.920319</td>
</tr>
<tr>
<th>Peak Spike</th>
<td>303</td>
<td>3.03</td>
<td>33.003300</td>
</tr>
<tr>
<th>Vape</th>
<td>272</td>
<td>2.72</td>
<td>36.764706</td>
</tr>
</tbody>
</table></body></html>

In [18]:
#2. parse the punk_facts

In [19]:
#3. find the table tag

In [20]:
#4. change the table tag class to the class we select in Bootstrap

In [21]:
#5. change font size, table size, etc if desired

In [22]:
#6. add link to Bootstrap to our html

## END