# Database Consolidation and Export to MongoDB Atlas

This notebook creates three consolidated MongoDB collections and exports them to our main MongoDB database store in MongoDB Atlas, 'crypto_punks_mdb':

* crypto_punks_col
* traders_col
* txn_history_col

### To manage the MongoDB Atlas database through MongoDB Compass, establish a connection using the following as the connection URI:

mongodb+srv://[user]:[password]@cluster0.wddnt.mongodb.net/[my_database]?retryWrites=true&w=majority"
    
Replace [user] and [password] for the cluster's user and password, and replace [my_database] with crypto_punks_mdb.

In [1]:
# Import main dependencies
import pandas as pd
import numpy as np
import json

# Import image handling libraries
from PIL import Image

# Import MongoDB libraries for database management 
import pymongo
from pymongo import MongoClient

import time

# Create a Connection to MongoDB Atlas

In [2]:
# Make a connection to Mongo with MongoClient (use this URI to establish 
# connection with MongoDB Atlas)

# 1. Get user and password for Atlas cluster connection
from config import user, password

# 2. Establish which database in the Atlas cluster to connect to
my_database = "crypto_punks_mdb"

atlas_path = "mongodb+srv://"+user+":"+password+"@cluster0.wddnt.mongodb.net/"+my_database+"?retryWrites=true&w=majority"

In [3]:
# 3. Establish the connection as a pyMongo client using the
# path to the cluster provided by your Atlas account
atlas_client = pymongo.MongoClient(atlas_path)

# 4. Verify connection was established
print(atlas_client.test)

Database(MongoClient(host=['cluster0-shard-00-01.wddnt.mongodb.net:27017', 'cluster0-shard-00-00.wddnt.mongodb.net:27017', 'cluster0-shard-00-02.wddnt.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-8x2to2-shard-0', tls=True), 'test')

In [4]:
# Create an object to point to the database
crypto_punks_mdb = atlas_client[my_database]

## 1. Consolidate the crypto_punks_col and Export to MongoDB Atlas

In [5]:
# Read the other dataframes to consolidate with:
type_predictions_df = pd.read_csv("Data/type_predictions.csv")
type_predictions_df

,punk_id,type,accessories,type_ML,type_PRED
0,0,Female,"['Green Eye Shadow', 'Earring', 'Blonde Bob']",1,1
1,1,Male,"['Smile', 'Mohawk']",0,0
2,2,Female,['Wild Hair'],1,1
3,3,Male,"['Wild Hair', 'Nerd Glasses', 'Pipe']",0,0
4,4,Male,"['Big Shades', 'Wild Hair', 'Earring', 'Goat']",0,0
...,...,...,...,...,...
9995,9995,Female,"['Purple Eye Shadow', 'Straight Hair Dark']",1,1
9996,9996,Male,"['Cigarette', 'Earring', 'Crazy Hair', 'Smile']",0,0
9997,9997,Zombie,"['Front Beard', 'Cap Forward']",2,2
9998,9998,Female,"['Wild White Hair', 'Black Lipstick', 'Clown E...",1,1
9999,9999,Female,"['Mohawk', 'Nerd Glasses']",1,1

In [6]:
# Read the other dataframes to consolidate with:
glasses_predictions_df = pd.read_csv("Data/glasses_predictions.csv")
glasses_predictions_df

,punk_id,type,accessories,glasses_ML,glasses_PRED
0,0,Female,"['Green Eye Shadow', 'Earring', 'Blonde Bob']",0,0
1,1,Male,"['Smile', 'Mohawk']",0,0
2,2,Female,['Wild Hair'],0,0
3,3,Male,"['Wild Hair', 'Nerd Glasses', 'Pipe']",1,1
4,4,Male,"['Big Shades', 'Wild Hair', 'Earring', 'Goat']",1,1
...,...,...,...,...,...
9995,9995,Female,"['Purple Eye Shadow', 'Straight Hair Dark']",0,0
9996,9996,Male,"['Cigarette', 'Earring', 'Crazy Hair', 'Smile']",0,0
9997,9997,Zombie,"['Front Beard', 'Cap Forward']",0,0
9998,9998,Female,"['Wild White Hair', 'Black Lipstick', 'Clown E...",0,0
9999,9999,Female,"['Mohawk', 'Nerd Glasses']",1,1

In [7]:
# Merge the dataframes
crypto_punks_consolidated_df = pd.merge(type_predictions_df, glasses_predictions_df, on=["punk_id","type","accessories"])
crypto_punks_consolidated_df

,punk_id,type,accessories,type_ML,type_PRED,glasses_ML,glasses_PRED
0,0,Female,"['Green Eye Shadow', 'Earring', 'Blonde Bob']",1,1,0,0
1,1,Male,"['Smile', 'Mohawk']",0,0,0,0
2,2,Female,['Wild Hair'],1,1,0,0
3,3,Male,"['Wild Hair', 'Nerd Glasses', 'Pipe']",0,0,1,1
4,4,Male,"['Big Shades', 'Wild Hair', 'Earring', 'Goat']",0,0,1,1
...,...,...,...,...,...,...,...
9995,9995,Female,"['Purple Eye Shadow', 'Straight Hair Dark']",1,1,0,0
9996,9996,Male,"['Cigarette', 'Earring', 'Crazy Hair', 'Smile']",0,0,0,0
9997,9997,Zombie,"['Front Beard', 'Cap Forward']",2,2,0,0
9998,9998,Female,"['Wild White Hair', 'Black Lipstick', 'Clown E...",1,1,0,0
9999,9999,Female,"['Mohawk', 'Nerd Glasses']",1,1,1,1

In [8]:
# Add url for punk_id description
for row in range(len(crypto_punks_consolidated_df)):
    #print("https://www.larvalabs.com/cryptopunks/details/"+str(row))
    crypto_punks_consolidated_df.at[row,"info_URL"]= "https://www.larvalabs.com/cryptopunks/details/"+str(row)

crypto_punks_consolidated_df

,punk_id,type,accessories,type_ML,type_PRED,glasses_ML,glasses_PRED,info_URL
0,0,Female,"['Green Eye Shadow', 'Earring', 'Blonde Bob']",1,1,0,0,https://www.larvalabs.com/cryptopunks/details/0
1,1,Male,"['Smile', 'Mohawk']",0,0,0,0,https://www.larvalabs.com/cryptopunks/details/1
2,2,Female,['Wild Hair'],1,1,0,0,https://www.larvalabs.com/cryptopunks/details/2
3,3,Male,"['Wild Hair', 'Nerd Glasses', 'Pipe']",0,0,1,1,https://www.larvalabs.com/cryptopunks/details/3
4,4,Male,"['Big Shades', 'Wild Hair', 'Earring', 'Goat']",0,0,1,1,https://www.larvalabs.com/cryptopunks/details/4
...,...,...,...,...,...,...,...,...
9995,9995,Female,"['Purple Eye Shadow', 'Straight Hair Dark']",1,1,0,0,https://www.larvalabs.com/cryptopunks/details/...
9996,9996,Male,"['Cigarette', 'Earring', 'Crazy Hair', 'Smile']",0,0,0,0,https://www.larvalabs.com/cryptopunks/details/...
9997,9997,Zombie,"['Front Beard', 'Cap Forward']",2,2,0,0,https://www.larvalabs.com/cryptopunks/details/...
9998,9998,Female,"['Wild White Hair', 'Black Lipstick', 'Clown E...",1,1,0,0,https://www.larvalabs.com/cryptopunks/details/...
9999,9999,Female,"['Mohawk', 'Nerd Glasses']",1,1,1,1,https://www.larvalabs.com/cryptopunks/details/...

In [9]:
# Inspect data types for compatibility with MongoDB
crypto_punks_consolidated_df.dtypes

punk_id          int64
type            object
accessories     object
type_ML          int64
type_PRED        int64
glasses_ML       int64
glasses_PRED     int64
info_URL        object
dtype: object

In [10]:
# Change incompatible data types
crypto_punks_consolidated_df = crypto_punks_consolidated_df.astype(str)
crypto_punks_consolidated_df.dtypes

punk_id         object
type            object
accessories     object
type_ML         object
type_PRED       object
glasses_ML      object
glasses_PRED    object
info_URL        object
dtype: object

In [11]:
crypto_punks_consolidated_df

,punk_id,type,accessories,type_ML,type_PRED,glasses_ML,glasses_PRED,info_URL
0,0,Female,"['Green Eye Shadow', 'Earring', 'Blonde Bob']",1,1,0,0,https://www.larvalabs.com/cryptopunks/details/0
1,1,Male,"['Smile', 'Mohawk']",0,0,0,0,https://www.larvalabs.com/cryptopunks/details/1
2,2,Female,['Wild Hair'],1,1,0,0,https://www.larvalabs.com/cryptopunks/details/2
3,3,Male,"['Wild Hair', 'Nerd Glasses', 'Pipe']",0,0,1,1,https://www.larvalabs.com/cryptopunks/details/3
4,4,Male,"['Big Shades', 'Wild Hair', 'Earring', 'Goat']",0,0,1,1,https://www.larvalabs.com/cryptopunks/details/4
...,...,...,...,...,...,...,...,...
9995,9995,Female,"['Purple Eye Shadow', 'Straight Hair Dark']",1,1,0,0,https://www.larvalabs.com/cryptopunks/details/...
9996,9996,Male,"['Cigarette', 'Earring', 'Crazy Hair', 'Smile']",0,0,0,0,https://www.larvalabs.com/cryptopunks/details/...
9997,9997,Zombie,"['Front Beard', 'Cap Forward']",2,2,0,0,https://www.larvalabs.com/cryptopunks/details/...
9998,9998,Female,"['Wild White Hair', 'Black Lipstick', 'Clown E...",1,1,0,0,https://www.larvalabs.com/cryptopunks/details/...
9999,9999,Female,"['Mohawk', 'Nerd Glasses']",1,1,1,1,https://www.larvalabs.com/cryptopunks/details/...

In [12]:
# Create an empty list to hold a dictionary for the records in the dataframe
crypto_punks_list = []

In [13]:
# Loop through the dataframe to populate the list while also adding the bitmap image
for row in range(len(crypto_punks_consolidated_df)):

    crypto_punks_list = []
    
    # Open the image file for the Crypto Punk id
    file_to_open = ("Data/images/"+str(row)+".png")
    rgb_image = Image.open(file_to_open)
    
    # Convert the image to a bitmap array as a list
    rgb_bit_map = np.asarray(rgb_image)
    
    # Convert the accessories field to a list
    # 1. Create an empty list
    accessories_list =[]
    # 2. Read the string with the accessories
    accessories = crypto_punks_consolidated_df.at[row,"accessories"]
    # 3. remove brackets, spaces and quotes
    accessories = accessories.replace("[","").replace(", ",",").replace("]","").replace("'","").replace("\"","")
    # 4. convert the string to a list
    accessories_list = accessories.split(",")
    
    
    # Add the punk_id data and bitmap array to the crypto_punks_list as
    # a dictionary
    crypto_punks_list.append({"punk_id": crypto_punks_consolidated_df.at[row,"punk_id"],
                              "type": crypto_punks_consolidated_df.at[row,"type"],
                              "accessories": accessories_list,
                              "type_ML": crypto_punks_consolidated_df.at[row,"type_ML"],
                              "type_PRED": crypto_punks_consolidated_df.at[row,"type_PRED"],
                              "glasses_ML": crypto_punks_consolidated_df.at[row,"glasses_ML"],
                              "glasses_PRED": crypto_punks_consolidated_df.at[row,"glasses_PRED"],
                              "info_URL": crypto_punks_consolidated_df.at[row,"info_URL"],
                              "image_bitmap": rgb_bit_map.tolist()
                             })
    
    
    # Add the crypto punk to the MongoDB in Atlas
    crypto_punks_mdb.crypto_punks_col.insert_one(crypto_punks_list[0])

In [14]:
# Inspect the first record of the list
crypto_punks_list[0]

{'punk_id': '9999',
 'type': 'Female',
 'accessories': ['Mohawk', 'Nerd Glasses'],
 'type_ML': '1',
 'type_PRED': '1',
 'glasses_ML': '1',
 'glasses_PRED': '1',
 'info_URL': 'https://www.larvalabs.com/cryptopunks/details/9999',
 'image_bitmap': [[[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [166, 110, 44, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [166, 110, 44, 255],
   [166, 110, 44, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [133, 86, 30, 255],
   [166, 110, 44, 255],
   [166, 110, 44, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [133, 86, 30, 255],
   [166, 110, 44, 255],
   [166, 110, 44, 255],
   [166, 110, 44, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [166, 110, 44, 255],
   [166, 110, 44, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [139, 83, 44, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [166, 110, 44, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [128, 219, 218, 255],
   [128, 219, 218, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [128, 219, 218, 255],
   [128, 219, 218, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [128, 219, 218, 255],
   [128, 219, 218, 255],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [128, 219, 218, 255],
   [128, 219, 218, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [74, 18, 1, 255],
   [74, 18, 1, 255],
   [74, 18, 1, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]],
  [[0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [113, 63, 29, 255],
   [0, 0, 0, 255],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0],
   [0, 0, 0, 0]]],
 '_id': ObjectId('61e486f3c34e5e3a5c6afebd')}

## 2. Export the traders_col to Mongo DB Atlas

In [15]:
# Read the traders.csv as a dataframe
traders_df = pd.read_csv("Data/traders.csv")
traders_df

,index,trader_id,txn_type,punk_id,eth,date,timestamp,source
0,4950,007,Bid,521,0.10,2019-12-17 00:00:00,2019-12-17 00:00:00,larvalabs
1,4949,007,Bid Withdrawn,521,0.10,2020-01-02 00:00:00,2020-01-02 00:00:00,larvalabs
2,126547,007,Purchased,7750,0.70,2020-04-07 00:00:00,2020-04-07 00:00:00,larvalabs
3,126545,007,Sold,7750,0.85,2020-04-08 00:00:00,2020-04-08 00:00:00,larvalabs
4,160412,0age.eth,Bid,9626,12.34,2021-06-09 00:00:00,2021-06-09 00:00:00,larvalabs
...,...,...,...,...,...,...,...,...
132521,118768,🤹🏻‍♂.e…,Bid,7334,89.00,2021-09-07 00:00:00,2021-09-07 00:00:00,larvalabs
132522,118764,🤹🏻‍♂.e…,Bid Withdrawn,7334,111.00,2021-09-08 00:00:00,2021-09-08 00:00:00,larvalabs
132523,118765,🤹🏻‍♂.e…,Bid,7334,111.00,2021-09-08 00:00:00,2021-09-08 00:00:00,larvalabs
132524,51870,🦊🦄👩‍?…,Purchased,3520,32.00,2021-07-31 00:00:00,2021-07-31 00:00:00,larvalabs
132525,51869,🦊🦄👩‍?…,Transfer,3520,0.00,2021-08-23 00:00:00,2021-08-23 00:00:00,larvalabs

In [16]:
# Inspect data types for compatibility with MongoDB
traders_df.dtypes

index          int64
trader_id     object
txn_type      object
punk_id        int64
eth          float64
date          object
timestamp     object
source        object
dtype: object

In [17]:
# Change incompatible data types
traders_df = traders_df.astype(str)
traders_df.dtypes

index        object
trader_id    object
txn_type     object
punk_id      object
eth          object
date         object
timestamp    object
source       object
dtype: object

In [18]:
# Reinspect the dataframe
traders_df

,index,trader_id,txn_type,punk_id,eth,date,timestamp,source
0,4950,007,Bid,521,0.1,2019-12-17 00:00:00,2019-12-17 00:00:00,larvalabs
1,4949,007,Bid Withdrawn,521,0.1,2020-01-02 00:00:00,2020-01-02 00:00:00,larvalabs
2,126547,007,Purchased,7750,0.7000000000000001,2020-04-07 00:00:00,2020-04-07 00:00:00,larvalabs
3,126545,007,Sold,7750,0.85,2020-04-08 00:00:00,2020-04-08 00:00:00,larvalabs
4,160412,0age.eth,Bid,9626,12.34,2021-06-09 00:00:00,2021-06-09 00:00:00,larvalabs
...,...,...,...,...,...,...,...,...
132521,118768,🤹🏻‍♂.e…,Bid,7334,89.0,2021-09-07 00:00:00,2021-09-07 00:00:00,larvalabs
132522,118764,🤹🏻‍♂.e…,Bid Withdrawn,7334,111.0,2021-09-08 00:00:00,2021-09-08 00:00:00,larvalabs
132523,118765,🤹🏻‍♂.e…,Bid,7334,111.0,2021-09-08 00:00:00,2021-09-08 00:00:00,larvalabs
132524,51870,🦊🦄👩‍?…,Purchased,3520,32.0,2021-07-31 00:00:00,2021-07-31 00:00:00,larvalabs
132525,51869,🦊🦄👩‍?…,Transfer,3520,0.0,2021-08-23 00:00:00,2021-08-23 00:00:00,larvalabs

In [19]:
# Create an empty list of dictionaries
traders_list=[]

In [20]:
# Loop through the dataframe to populate the list while also adding the bitmap image
for row in range(len(traders_df)):

    # Add the trader data to the traders_list as
    # a dictionary
    traders_list.append({"txn_index": traders_df.at[row,"index"],
                         "trader_id": traders_df.at[row,"trader_id"],
                         "txn_type": traders_df.at[row,"txn_type"],
                         "punk_id": traders_df.at[row,"punk_id"],
                         "eth": traders_df.at[row,"eth"],
                         "date": traders_df.at[row,"date"],
                         "timestamp": traders_df.at[row,"timestamp"],
                         "source": traders_df.at[row,"source"]
                        })

In [21]:
# Inspect the first record of the list
traders_list[0]

{'txn_index': '4950',
 'trader_id': '007',
 'txn_type': 'Bid',
 'punk_id': '521',
 'eth': '0.1',
 'date': '2019-12-17 00:00:00',
 'timestamp': '2019-12-17 00:00:00',
 'source': 'larvalabs'}

In [30]:
# Add the txn_history as a collection to the database 10,000 records at a time

for runs in range(133):
    start_record = runs*1000
    end_record = 1000 + runs*1000
    if end_record >= 132527:
        end_record = 132526
    print("processing record: ",start_record,"  to: ",end_record)

    # Select the batch to be loaded
    list_to_load = traders_list[start_record:end_record]
  
    # upload the batch to the database collection
    crypto_punks_mdb.traders_col.insert_many(list_to_load)

# Report when done
print ("Export completed ----------------------------")

processing record:  0   to:  1000
processing record:  1000   to:  2000
processing record:  2000   to:  3000
processing record:  3000   to:  4000
processing record:  4000   to:  5000
processing record:  5000   to:  6000
processing record:  6000   to:  7000
processing record:  7000   to:  8000
processing record:  8000   to:  9000
processing record:  9000   to:  10000
processing record:  10000   to:  11000
processing record:  11000   to:  12000
processing record:  12000   to:  13000
processing record:  13000   to:  14000
processing record:  14000   to:  15000
processing record:  15000   to:  16000
processing record:  16000   to:  17000
processing record:  17000   to:  18000
processing record:  18000   to:  19000
processing record:  19000   to:  20000
processing record:  20000   to:  21000
processing record:  21000   to:  22000
processing record:  22000   to:  23000
processing record:  23000   to:  24000
processing record:  24000   to:  25000
processing record:  25000   to:  26000
processing record:  26000   to:  27000
processing record:  27000   to:  28000
processing record:  28000   to:  29000
processing record:  29000   to:  30000
processing record:  30000   to:  31000
processing record:  31000   to:  32000
processing record:  32000   to:  33000
processing record:  33000   to:  34000
processing record:  34000   to:  35000
processing record:  35000   to:  36000
processing record:  36000   to:  37000
processing record:  37000   to:  38000
processing record:  38000   to:  39000
processing record:  39000   to:  40000
processing record:  40000   to:  41000
processing record:  41000   to:  42000
processing record:  42000   to:  43000
processing record:  43000   to:  44000
processing record:  44000   to:  45000
processing record:  45000   to:  46000
processing record:  46000   to:  47000
processing record:  47000   to:  48000
processing record:  48000   to:  49000
processing record:  49000   to:  50000
processing record:  50000   to:  51000
processing record:  51000   to:  52000
processing record:  52000   to:  53000
processing record:  53000   to:  54000
processing record:  54000   to:  55000
processing record:  55000   to:  56000
processing record:  56000   to:  57000
processing record:  57000   to:  58000
processing record:  58000   to:  59000
processing record:  59000   to:  60000
processing record:  60000   to:  61000
processing record:  61000   to:  62000
processing record:  62000   to:  63000
processing record:  63000   to:  64000
processing record:  64000   to:  65000
processing record:  65000   to:  66000
processing record:  66000   to:  67000
processing record:  67000   to:  68000
processing record:  68000   to:  69000
processing record:  69000   to:  70000
processing record:  70000   to:  71000
processing record:  71000   to:  72000
processing record:  72000   to:  73000
processing record:  73000   to:  74000
processing record:  74000   to:  75000
processing record:  75000   to:  76000
processing record:  76000   to:  77000
processing record:  77000   to:  78000
processing record:  78000   to:  79000

AutoReconnect: cluster0-shard-00-02.wddnt.mongodb.net:27017: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2633)

## 3. Export the txn_history_col to Mongo DB Atlas

In [ ]:
# Read the traders.csv as a dataframe
txn_history_df = pd.read_csv("Data/tx_history.csv")
txn_history_df

In [ ]:
# Inspect data types for compatibility with MongoDB
txn_history_df.dtypes

In [ ]:
# Change incompatible data types
txn_history_df = txn_history_df.astype(str)
txn_history_df.dtypes

In [ ]:
# Reinspect the dataframe
txn_history_df

In [ ]:
# Create an empty list of dictionaries
txn_history_list=[]

In [ ]:
# Loop through the dataframe to populate the list
for row in range(len(txn_history_df)):

    # Add the transaction history data to the txn_history_list as
    # a dictionary
    txn_history_list.append({"txn_index": str(row),
                             "txn_type": txn_history_df.at[row,"txn_type"],
                             "from": txn_history_df.at[row,"from"],
                             "to": txn_history_df.at[row,"to"],
                             "date": txn_history_df.at[row,"date"],
                             "timestamp": txn_history_df.at[row,"timestamp"],
                             "source": txn_history_df.at[row,"source"],
                             "eth": txn_history_df.at[row,"eth"],
                             "punk_id": txn_history_df.at[row,"punk_id"],
                             "from_wallet_address": txn_history_df.at[row,"from_wallet_address"],
                             "to_wallet_address": txn_history_df.at[row,"to_wallet_address"]
                            })

In [ ]:
# Inspect the first record of the list
txn_history_list[0]

In [ ]:
# Add the txn_history as a collection to the database 1,000 records at a time

for runs in range(168):
    start_record = runs*1000
    end_record = 1000 + runs*1000
    if end_record >= 167493:
        end_record = 167492
    print("processing record: ",start_record,"  to: ",end_record)

    # Select the batch to be loaded
    list_to_load = txn_history_list[start_record:end_record]
  
    # upload the batch to the database collection
    crypto_punks_mdb.txn_history_col.insert_many(list_to_load)

# Report when done
print ("Export completed ----------------------------")

# END